# Site settings
title: Abraxas
description: The bird fights its way out of the egg
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Boram Lee
user_description: "Hello, I’m Boram Lee. \
 I am passionate about Artificial Intelligence, particularly in analyzing physiological data like EEG and ECG, and developing wearable healthcare solutions. My background includes research and journal publications in EEG and ECG, a master’s degree in Brain and Cognitive Engineering, and five years of experience managing data science projects in NLP. I also developed an AI-powered healthcare application for seniors, focusing on mental health and medication management. In my free time, \
 \
 I enjoy movies, exploring new places, and spending time with animals."
user_title: Data Scientist
email: boramlee0418@gmail.com
github_username:  boramlee0418@gmail.com
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
